### ISSUE TITLE
Question about the maxConnections prop

### ISSUE THREAD

**Issue by AlexHramovich** [MatteoGioioso/serverless-pg#48]
Could you please explain how it works?

For example:
I have a DB with constant 3 connections. If I would like to work with this database using this library and maxConnections = 5. Does this mean that persistent connections can be closed if I, for example, try to open 5 new connections ?

**Comment by AlexHramovich** [comment]
It looks like .clean () closes all existing db connections. Is it possible to close only the current DB connection ?

**Comment by MatteoGioioso** [comment]
Hello, `.clean()` closes all the idle connections (depending on `minConnectionIdleTimeSec`) **if the threshold is reached**, by default `connUtilization` is 80% of 100 `maxConnections`.

If you wish to close only the current DB connection you just use the `.end()` instead of `.close()`: https://node-postgres.com/api/client
But at this point I just would use node-pg instead of this library, unless you want to leverage the query and client retries functionality.
